#ifndef _CONFIG_H_
#define _CONFIG_H_

#define PI 3.14159265358979323846

#define VENTANA_ANCHO 800
#define VENTANA_ALTO 600


#define MARGEN_ALTURA 0.7
#define MARGEN_ANCHO 0.7
#define MARGEN_NIVEL_FIJO 0.9
#define ESCALA_MINIMA 0.6

#define JUEGO_FPS 100

#define JUEGO_COMBUSTIBLE_INICIAL 10000
#define JUEGO_COMBUSTIBLE_POT_X_SEG 250
#define JUEGO_COMBUSTIBLE_ESC_X_SEG 500

#define DISTANCIA_TORRETA_DISPARAR  100

#define COOLDOWN_TORRETA    5
#define COOLDOWN_NAVE       0.5

#define VELOCIDAD_DISPARO   150

#define DT 1.f/JUEGO_FPS

#define G 10

#define NAVE_ROTACION_PASO (PI/20)
#define NAVE_ACELERACION (10*G)

#define NAVE_ANGULO_INICIAL (PI/2)

#define MAXIMO_TIEMPO_DISPARO   30

#define CANTIDAD_COMBUSTIBLE_INICIAL 10000

#define PUNTAJE_CHECKPOINT  10000

#define TIEMPO_REACTOR 100.0


#endif // _CONFIG_H_

